### PR TITLE
Feature/psilord/collision tests

### PR DESCRIPTION
**Pull request by psilord**
Complete enough of the collision system that we can use it for games.

It has been tested to about 75% of the edge cases or so. 

There is a new scene which demonstrates the code: collision-simple-destroy-0

### CODE REVIEW

**Comment by mfiano** [comment]
Looks good to me. Can you document these tests you ran? I think doing the other 25% or so is beneficial before we merge this.

**Comment by psilord** [comment]
Ok I'll see about writing the remaining tests and maybe some non-general purpose code to automate it.

**Comment by mfiano** [comment]
Sure. It doesn't have to be in a specific branch for the jam. We can base the jam game off of a specific branch or union of multiple.

**Comment by psilord** [comment]
I added a new scene and tested:

1) colliders that should be colliding in frame 0 indeed to collide.
2) colliders enter/continue/exit properly with other colliders while colliders are moving.
3) colliders can trigger a destruction of an actor when colliding and the actor destroys correctly.
4) The visualization of the colliders are correct.

**Comment by psilord** [comment]
So, if you like the commits and it works on your machine, I propose acceptance of the PR.

**Pull request merged**
